### ISSUE TITLE
it shows just from View.

### ISSUE THREAD

**Issue by uzman** [pchernovolenko/UICustomActionSheet#4]
Hi,
it can not be used with uinavigationbar and tabbarcontroller.
there is just showInView method.

can you add showFromTabbar like default action sheet?

**Comment by pchernovolenko** [comment]
Hi,

It behaves like default UIActionSheet. So, if you want to use it with UINavigationController or UITabBarController try to write this `[actionSheet showInView:self.tabBarController.view];`
